import { useEffect, useRef, useState } from 'react';
import { Activity, ArrowDown, ArrowRight, BookOpen, Check, ClipboardList, FileText, FlaskConical, Heart, Hospital, Layers3, LockKeyhole, Menu, MessageCircle, Pill, ShieldCheck, Smartphone, Sparkles, Stethoscope, TrendingUp, UserRound, X } from 'lucide-react';
import { gsap } from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogTitle } from '@/components/ui/dialog';
import { Brand, ConnectedTimeline, DoctorPreview, HeroProduct, LogoMark, PatientPreview, SharingPreview } from './product-visuals';

type DialogKind = 'start' | 'signin' | 'clinic' | 'patient' | 'doctor' | null;
const navigation = [['How it works','how-it-works'],['For patients','for-patients'],['For doctors','for-doctors'],['Privacy','privacy']];
const dialogContent = {
  start: { title: 'Start with your clinic.', description: 'Inlay Health begins with an invitation from your clinic. Ask your care team whether they offer Inlay Health.', detail: 'Already invited? Use the secure link in your invitation to set up your account. You choose whether to share before records are collected.', icon: Hospital },
  signin: { title: 'Your invitation is the way in.', description: 'A sign-in destination has not been provided for this website yet.', detail: 'If your clinic has invited you to Inlay Health, use the access link they sent you. Contact your clinic if you need help finding it.', icon: LockKeyhole },
  clinic: { title: 'A connected view for your clinic.', description: 'Inlay Health helps patients and doctors review the same up-to-date health information, with patient permission.', detail: 'Clinic onboarding is not available through this website yet. Patients join through a clinic invitation; records are collected only after they agree.', icon: Stethoscope },
  patient: { title: 'More clarity. More control.', description: 'Bring available health records together, follow changes, and take better-informed questions to your doctor.', detail: 'Your experience includes health trends, missed-test reminders, Ask Inlay, and sharing controls. Availability depends on your clinic, supported sources, and plan.', icon: UserRound },
  doctor: { title: 'The whole picture, at a glance.', description: 'Review changes in records, medication discrepancies, and missed follow-ups in one connected view.', detail: 'Your clinic’s patients remain within clear access boundaries. AI surfaces information for review; you remain responsible for clinical decisions.', icon: Stethoscope },
};

export function InlayHomepage() {
  const [mobileOpen, setMobileOpen] = useState(false);
  const [dialog, setDialog] = useState<DialogKind>(null);
  const pageRef = useRef<HTMLDivElement>(null);
  useEffect(() => {
    if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return;
    gsap.registerPlugin(ScrollTrigger);
    const context = gsap.context(() => {
      gsap.from('[data-hero]', { y: 20, opacity: 0, duration: .65, stagger: .09, ease: 'power2.out', clearProps: 'all' });
      gsap.utils.toArray<HTMLElement>('[data-reveal]').forEach(el => {
        gsap.from(el, { y: 24, duration: .6, ease: 'power2.out', scrollTrigger: { trigger: el, start: 'top 92%', once: true }, clearProps: 'transform' });
      });
      gsap.from('.source-card', { x: -14, stagger: .1, duration: .5, ease: 'power2.out', scrollTrigger: { trigger: '.record-network', start: 'top 85%', once: true }, clearProps: 'transform' });
      gsap.from('.network-lines path', { strokeDasharray: 220, strokeDashoffset: 220, duration: .7, stagger: .1, scrollTrigger: { trigger: '.record-network', start: 'top 85%', once: true }, clearProps: 'all' });
    }, pageRef);
    return () => context.revert();
  }, []);
  useEffect(() => {
    if (!mobileOpen) return;
    const close = (event: KeyboardEvent) => { if (event.key === 'Escape') setMobileOpen(false); };
    window.addEventListener('keydown', close);
    return () => window.removeEventListener('keydown', close);
  }, [mobileOpen]);
  const activeDialog = dialog ? dialogContent[dialog] : null;
  return <div ref={pageRef} id="top">
    <a href="#main" className="sr-only focus:not-sr-only focus:fixed focus:top-3 focus:left-3 focus:z-50 focus:bg-background focus:p-3">Skip to content</a>
    <header className="site-header"><div className="container-shell header-inner"><Brand linked /><nav className="header-nav" aria-label="Main navigation">{navigation.map(([label,id]) => <a href={`#${id}`} key={id}>{label}</a>)}</nav><div className="header-actions"><Button variant="quiet" className="header-signin" onClick={() => setDialog('signin')}>Sign in</Button><Button variant="brand" size="lg" className="header-cta" onClick={() => setDialog('start')}>Get started <ArrowUpIcon /></Button><Button variant="quiet" size="icon" className="mobile-menu" aria-label={mobileOpen ? 'Close menu' : 'Open menu'} aria-expanded={mobileOpen} aria-controls="mobile-navigation" onClick={() => setMobileOpen(!mobileOpen)}>{mobileOpen ? <X /> : <Menu />}</Button></div></div>{mobileOpen && <nav className="mobile-nav" id="mobile-navigation" aria-label="Mobile navigation">{navigation.map(([label,id]) => <a href={`#${id}`} key={id} onClick={() => setMobileOpen(false)}>{label}</a>)}<Button variant="quiet" className="justify-start px-0" onClick={() => { setDialog('signin'); setMobileOpen(false); }}>Sign in <ArrowRight /></Button></nav>}</header>
    <main id="main">
      <section className="hero"><div className="container-shell"><div className="eyebrow" data-hero>A little more connected. A lot more clear.</div><h1 className="display-heading" data-hero>Your health,<br /><span className="text-primary">all in one place.</span></h1><p className="body-copy hero-copy" data-hero>Bring your medical records together, understand what’s changing, and help your doctor see the bigger picture.</p><div className="hero-actions" data-hero><Button variant="brand" size="lg" onClick={() => setDialog('start')}>Get started <ArrowRight /></Button><Button variant="quiet" size="lg" asChild><a href="#how-it-works">See how it works <ArrowDown /></a></Button></div><div className="hero-stage" data-hero><HeroProduct /><div className="hero-caption"><LockKeyhole size={12} /> Connected with your permission. Made for your care.</div></div><div className="hero-trust"><span><Layers3 /> One connected health record</span><span><Sparkles /> Clarity, with AI assistance</span><span><ShieldCheck /> Patient-controlled sharing</span></div></div></section>
      <section className="section-space" id="how-it-works"><div className="container-shell"><div className="section-intro center" data-reveal><span className="eyebrow"><Layers3 /> From scattered to connected</span><h2 className="section-heading">Your health story is scattered.</h2><p className="body-copy">Test results, prescriptions, and hospital records.<br className="hidden sm:block" /> Different places. One person. You.</p></div><div className="record-network" data-reveal><div className="source-grid">{[{icon:Hospital,title:'Hospital records',sub:'Visits & clinical notes'},{icon:FlaskConical,title:'Lab results',sub:'Tests & reports'},{icon:Pill,title:'Prescriptions',sub:'Your medications'},{icon:Smartphone,title:'Health data',sub:'From your phone'}].map(({icon:Icon,title,sub}) => <div className="source-card" key={title}><Icon /><div><strong>{title}</strong><small>{sub}</small></div></div>)}</div><svg className="network-lines" viewBox="0 0 130 160" preserveAspectRatio="none" aria-hidden="true"><path d="M0 35 H35 Q65 35 65 80 H130" /><path d="M0 125 H35 Q65 125 65 80 H130" /><circle cx="125" cy="80" r="3" /></svg><div className="unified-card"><Brand /><h3>One connected health record.</h3><p>Every available piece, in the right place.</p><div className="unified-status"><Check size={13} /> Together, with your permission</div></div></div><p className="section-footnote">Available records from supported sources, collected only with your permission.</p></div></section>
      <section className="connected-section section-space"><div className="container-shell split-section"><div className="split-copy" data-reveal><span className="eyebrow"><Activity /> The bigger picture</span><h2 className="section-heading">See the whole picture,<br />not isolated results.</h2><p className="body-copy">A connected timeline brings context to your health. See what changed, where it came from, and what may need attention.</p><a className="text-link" href="#intelligence">Make sense of your records <ArrowRight /></a></div><div data-reveal><ConnectedTimeline /><p className="section-footnote">Your records, organized. Not a replacement for clinical systems.</p></div></div></section>
      <section className="dark-section section-space" id="intelligence"><div className="container-shell"><div className="ai-section-top" data-reveal><div><span className="eyebrow"><Sparkles /> A clearer understanding</span><h2 className="section-heading">Health information,<br />made easier to understand.</h2></div><p className="body-copy">Less medical jargon. More useful context.<br />See what your results say and what may need a closer look.</p></div><div className="ai-capabilities" data-reveal>{[{icon:BookOpen,title:'Understand results',copy:'Plain-language explanations of the information in your records.'},{icon:TrendingUp,title:'Spot changes',copy:'See trends and results that may be worth discussing.'},{icon:ClipboardList,title:'Find care gaps',copy:'Keep missed tests and follow-ups from getting lost.'}].map(({icon:Icon,title,copy}) => <div className="ai-capability" key={title}><Icon /><h3>{title}</h3><p>{copy}</p></div>)}</div><div className="ask-demo" data-reveal><div><div className="ai-summary-title"><MessageCircle size={17} /> Ask Inlay</div><p className="ask-question">“What does my HbA1c<br className="hidden sm:block" /> result tell me?”</p></div><div className="ask-response"><div className="ai-summary-title"><Sparkles size={16} /> A little context can help.</div><p>HbA1c reflects your average blood sugar over roughly three months. Your latest result is 5.8%, compared with 6.2% in April.</p><p>Your doctor can explain what that change means for your care.</p><small>Illustrative AI response · Not a diagnosis or medical advice</small></div></div><p className="dark-footnote">AI helps you understand. Medical decisions stay with your doctor.</p></div></section>
      <section className="section-space"><div className="container-shell"><div className="section-intro center" data-reveal><span className="eyebrow"><Heart /> Better-informed care, together</span><h2 className="section-heading">Two perspectives.<br />One health picture.</h2><p className="body-copy">The same connected information.<br />A thoughtful experience for each side of care.</p></div><div className="audience-grid"><article className="audience-block" id="for-patients" data-reveal><div className="audience-demo"><PatientPreview /></div><div className="audience-copy"><span className="eyebrow">For patients</span><h3 className="card-heading">Know more about your health.</h3><p>Find your records, follow your trends, and bring better questions to your next conversation. You decide what to share.</p><Button variant="link" className="px-0 mt-4" onClick={() => setDialog('patient')}>Explore the patient experience <ArrowRight /></Button></div></article><article className="audience-block" id="for-doctors" data-reveal><div className="audience-demo"><DoctorPreview /></div><div className="audience-copy"><span className="eyebrow">For doctors</span><h3 className="card-heading">See what needs attention.</h3><p>A concise view of new results, medication discrepancies, and missed follow-ups—so you can focus on the person behind the record.</p><Button variant="link" className="px-0 mt-4" onClick={() => setDialog('doctor')}>Explore the doctor experience <ArrowRight /></Button></div></article></div><p className="section-footnote">Product illustrations use fictional records and sample results.</p></div></section>
      <section className="workflow-section section-space" id="getting-started"><div className="container-shell"><div className="section-intro center" data-reveal><span className="eyebrow"><Check /> Simple from the start</span><h2 className="section-heading">Connected by permission.<br />Guided by care.</h2><p className="body-copy">A clear path from your clinic to a more connected record.</p></div><div className="workflow-grid" data-reveal>{[['Join through your clinic','Your clinic sends you an invitation.'],['Set up your account','Follow your invitation to secure your access.'],['Choose to share','Give permission before records are collected.'],['Understand together','Review your health information with your doctor.']].map(([title,copy],i) => <div className="workflow-step" key={title}><span className="step-number">0{i+1}</span><h3>{title}</h3><p>{copy}</p></div>)}</div><div className="permission-note"><ShieldCheck /> Your choice stays yours. Withdraw permission at any time.</div></div></section>
      <section className="section-space" id="privacy"><div className="container-shell privacy-layout"><div data-reveal><span className="eyebrow"><ShieldCheck /> Trust, by design</span><h2 className="section-heading">Your health information.<br />Under your control.</h2><div className="privacy-points">{[{icon:Check,title:'Permission first',copy:'Records are collected only after you agree. You can withdraw that permission.'},{icon:LockKeyhole,title:'Clear access boundaries',copy:'Each clinic sees its own patients. Office staff do not see medical information.'},{icon:FileText,title:'Accountability built in',copy:'Access and changes are recorded so activity can be traced.'}].map(({icon:Icon,title,copy}) => <div className="privacy-point" key={title}><Icon /><div><h3>{title}</h3><p>{copy}</p></div></div>)}</div></div><div data-reveal><SharingPreview /><p className="section-footnote">Sharing illustration · Patient permission comes first</p></div></div></section>
      <section className="section-space capabilities-section" id="capabilities"><div className="container-shell"><div className="capabilities-heading" data-reveal><div><span className="eyebrow"><Layers3 /> Thoughtfully connected</span><h2 className="section-heading">The details that<br />make the difference.</h2></div><p className="body-copy">Useful tools for understanding your health.<br />Built around the information you already have.</p></div><div className="capabilities-grid" data-reveal>{[{icon:FileText,title:'Unified health records',copy:'Available records, organized in one coherent view.'},{icon:TrendingUp,title:'Trends & result warnings',copy:'See changes over time and results that may need review.'},{icon:ClipboardList,title:'Missed-test reminders',copy:'Keep important tests and follow-ups in view.'},{icon:Pill,title:'Medication comparison',copy:'Surface differences in medication records for clinical review.'},{icon:MessageCircle,title:'Ask Inlay',copy:'Get plain-language context for your health information.'},{icon:Heart,title:'Personal health plans',copy:'Doctor-reviewed plans, with availability depending on your plan.'}].map(({icon:Icon,title,copy}) => <article className="capability-card" key={title}><Icon /><h3>{title}</h3><p>{copy}</p></article>)}</div><p className="section-footnote">Capabilities vary by clinic and plan. Some may require a paid plan.</p></div></section>
      <section className="final-section" id="get-started"><div className="container-shell" data-reveal><LogoMark /><h2 className="section-heading">A clearer picture of your health<br className="hidden sm:block" /> starts here.</h2><p className="body-copy">Bring your records together. Make your next conversation with your doctor a more informed one.</p><div className="hero-actions"><Button variant="brand" size="lg" onClick={() => setDialog('start')}>Get started <ArrowRight /></Button><Button variant="quiet" size="lg" onClick={() => setDialog('clinic')}>For clinics <ArrowRight /></Button></div></div></section>
    </main>
    <footer><div className="container-shell"><div className="footer-main"><div className="footer-brand"><Brand linked /><p>A connected view of your health.<br />More clarity for you. More context for your doctor.</p></div><div className="footer-links"><strong>Platform</strong><a href="#how-it-works">How it works</a><a href="#capabilities">Capabilities</a><a href="#intelligence">Ask Inlay</a></div><div className="footer-links"><strong>Made for you</strong><a href="#for-patients">For patients</a><a href="#for-doctors">For doctors</a><Button variant="quiet" onClick={() => setDialog('clinic')}>For clinics</Button></div><div className="footer-links"><strong>Your Inlay</strong><a href="#privacy">Privacy & control</a><Button variant="quiet" onClick={() => setDialog('signin')}>Sign in</Button><a href="#getting-started">Getting started</a></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Inlay Health. All rights reserved.</span><span>Connected information. Human-led care.</span></div></div></footer>
    <Dialog open={dialog !== null} onOpenChange={open => { if (!open) setDialog(null); }}><DialogContent className="informational-dialog">{activeDialog && <><span className="icon-tile"><activeDialog.icon /></span><DialogTitle>{activeDialog.title}</DialogTitle><DialogDescription>{activeDialog.description}</DialogDescription><div className="dialog-detail"><ShieldCheck /><span>{activeDialog.detail}</span></div><Button variant="brand" size="lg" asChild><a href={dialog === 'clinic' || dialog === 'doctor' ? '#for-doctors' : '#getting-started'} onClick={() => setDialog(null)}>See how it works <ArrowRight /></a></Button></>}</DialogContent></Dialog>
  </div>;
}
function ArrowUpIcon() { return <ArrowRight className="-rotate-45" />; }
